# Generated by Django 4.2.5 on 2023-10-10 16:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="catagery",
            name="category",
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
