# Generated by Django 4.2.5 on 2023-10-12 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0002_feedback"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="")),
            ],
        ),
    ]
