# Generated by Django 4.2.5 on 2023-10-13 02:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0003_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(upload_to="product_images/"),
        ),
    ]
