# Generated by Django 4.2.5 on 2023-10-13 07:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0004_alter_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
