# Generated by Django 4.2.5 on 2023-10-13 13:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0005_product_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="company_name",
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="first_name",
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="last_name",
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
