# Generated by Django 4.2.5 on 2023-10-13 13:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0007_customuser"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
