# Generated by Django 4.2.5 on 2023-10-13 15:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0008_delete_customuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="Catageory",
            field=models.CharField(
                choices=[
                    ("Vegetable", "Vegetable"),
                    ("Fruit", "Fruit"),
                    ("Seeds", "Seeds"),
                    ("Others", "Others"),
                ],
                default=0,
                max_length=100,
            ),
            preserve_default=False,
        ),
    ]
