# Generated by Django 4.2.5 on 2023-10-13 17:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0009_product_catageory"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="password2",
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
