# Generated by Django 4.2.5 on 2023-10-14 09:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0011_alter_user_first_name_alter_user_last_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="password2",
        ),
    ]
