# Generated by Django 4.2.5 on 2023-10-14 10:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0013_customuser"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="company_name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="last_name",
        ),
        migrations.AddField(
            model_name="user",
            name="password2",
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="password1",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
