# Generated by Django 4.2.5 on 2023-10-14 11:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0014_remove_user_company_name_remove_user_first_name_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CartItem",
        ),
    ]
