# Generated by Django 4.2.5 on 2023-10-14 12:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0015_delete_cartitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="district",
            field=models.CharField(
                choices=[
                    ("Guntur", "Guntur"),
                    ("Krishna", "Krishna"),
                    ("Kadapa", "Kadapa"),
                    ("Others", "Others"),
                ],
                default=0,
                max_length=100,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="state",
            field=models.CharField(
                choices=[
                    ("Andhra Pradesh", "Andhra Pradesh"),
                    ("Tamil Nadu", "Tamil Nadu"),
                    ("Kerala", "Kerala"),
                    ("Karanataka", "Karanataka"),
                    ("Others", "Others"),
                ],
                default=0,
                max_length=100,
            ),
            preserve_default=False,
        ),
    ]
