# Generated by Django 4.2.5 on 2023-10-20 02:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0020_transaction_remove_payment_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="phone",
            field=models.CharField(max_length=10),
        ),
    ]
