# Generated by Django 4.2.5 on 2023-10-28 10:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0021_alter_product_phone"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Transaction",
        ),
    ]
