# Generated by Django 4.2.5 on 2023-10-28 12:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0022_delete_transaction"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_id", models.CharField(max_length=100)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
